name: petclinic work

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
        name: petclinic 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: list repo files 
          run: ls -ltra

        - name: Executing shell script 
          run: |
            chmod +x petclinic-shell-script.sh
            ./petclinic-shell-script.sh
        - name: uploading petclinic.war file 
          uses: actions/upload-artifact@v4
          with:
            name: petclinic.war
            path: /home/runner/work/petclinic-k8s/petclinic-k8s/target/petclinic.war


    deployment:
        needs: unit-testing
        name: petclinic-deployment
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: list repo files 
          run: ls -ltra

        - name: Executing shell script 
          run: |
            chmod +x tomcat.sh
            ./tomcat.sh

        - name: download petclinic.war file 
          uses: actions/download-artifact@v4
          with:
            name: petclinic.war
        - name: list directory 
          run: ls

        - name: check path
          run: pwd
        - name: copy petclink war file in webapps 
          run: cp /home/runner/work/petclinic-k8s/petclinic-k8s/petclinic.war /opt/tomcat/webapps
        - name: deployment check
          run: cd /opt/tomcat/webapps
        - name: check files
          run: pwd




          